import { VideoData } from '../shared/domain/model';

export const VIDEO_DATA: VideoData[] = [
  {
    id: 'SCj_nf3n9Mo',
    title: 'アイドルが絶対に笑ってはいけないTikTokやってみた結果www #14',
    viewCount: 250,
    memberNames: ['桜瀬もえ', '夏生のん', '渡辺栞', '藤咲はな'],
  },
  {
    id: '3cPolrsXU7I',
    title: 'バラエティNG？アイドルの苦手なものを調査してみたらまさかの事実が発覚しました。 #13',
    viewCount: 595,
    memberNames: ['桜瀬もえ', '夏生のん', '大嶋ひかり', '藤咲はな', '雪咲みうな'],
  },
  {
    id: 'Ya0GdgCSVaU',
    title: '【アイドルの休日密着】彼女とイルミネーションデートなうに使っていいよ',
    viewCount: 608,
    memberNames: ['夏生のん', '双葉みきな'],
  },
  {
    id: 'yxxlZOKrtu0',
    title: 'ふざけすぎ？！メンバーのあだ名を整理してみた結果www #12',
    viewCount: 538,
    memberNames: ['夏生のん', '美和花樺', '双葉みきな', '渡辺栞', '大嶋ひかり', '加藤伶奈'],
  },
  {
    id: 'taDLwARgKmI',
    title: 'やる気のないMCが突然ブチギレて帰ったらメンバーはどんな反応をする？【ドッキリ】 #11',
    viewCount: 699,
    memberNames: ['桜瀬もえ', '夏生のん', '美和花樺', '双葉みきな', '渡辺栞', '大嶋ひかり', '藤咲はな'],
  },
  {
    id: 'vlvFkMOXMXk',
    title: '【心理テスト】アイドルの内面が丸裸に！？外見に対する自信を調査してみた結果…！ #10',
    viewCount: 528,
    memberNames: ['美和花樺', '双葉みきな', '藤咲はな', '南ララ'],
  },
  {
    id: 'YgWzy9DF3zg',
    title: '奇行に走るアイドル！？第1回企画プレゼン大会！【企画募集】 #9',
    viewCount: 600,
    memberNames: ['桜瀬もえ', '美和花樺', '双葉みきな', '藤咲はな'],
  },
  {
    id: 'eh_DBpk1dlA',
    title: 'アイドルの画力はいかに！？お絵描き対決でとんでもない画伯が誕生したwww #8',
    viewCount: 548,
    memberNames: ['桜瀬もえ', '夏生のん', '渡辺栞', '南ララ'],
  },
  {
    id: 'c6gcajkNODw',
    title: '卒アル公開で放送事故？！アイドルの卒業アルバム写真が衝撃的すぎたwww #7',
    viewCount: 1232,
    memberNames: ['夏生のん', '渡辺栞', '大嶋ひかり', '藤咲はな'],
  },
  {
    id: 'Qyp6R9v-lqY',
    title: '【アイドルの裏側】さくらシンデレラデビュー５周年記念ワンマンライブの裏側に密着！',
    viewCount: 1475,
    memberNames: [
      '小鳥遊七星',
      '桜瀬もえ',
      '夏生のん',
      '美和花樺',
      '星野雫',
      '双葉みきな',
      '渡辺栞',
      '大嶋ひかり',
      '藤咲はな',
      '南ララ',
      '加藤伶奈',
      '雪咲みうな',
      '成瀬あいな',
      '水越菜波',
      '望月みらん',
      '西野蓮',
    ],
  },
  {
    id: 'fCdVe9cBGac',
    title: 'アイドル達に人生の黒歴史を聞いてみたら放送禁止レベルだったwww #6',
    viewCount: 1190,
    memberNames: ['桜瀬もえ', '夏生のん', '美和花樺', '双葉みきな'],
  },
  {
    id: 'R0TrTssG7RA',
    title: 'アイドルの検索履歴を抜き打ちでチェックした結果がやばかったwwww #5',
    viewCount: 845,
    memberNames: ['双葉みきな', '大嶋ひかり', '藤咲はな', '南ララ'],
  },
  {
    id: 'MaiDs7z27A8',
    title: '【アイドル抜き打ち学力テスト】珍回答連発！一番バカなのはだれ！？',
    viewCount: 1125,
    memberNames: ['桜瀬もえ', '渡辺栞', '大嶋ひかり', '南ララ'],
  },
  {
    id: 'vUKMKi9yG-0',
    title: '【放送事故】アイドルのライブ中に起きたハプニングがヤバすぎたwww #3',
    viewCount: 2579,
    memberNames: ['夏生のん', '美和花樺', '渡辺栞', '大嶋ひかり'],
  },
  {
    id: '31z5wpECzC0',
    title: '個性爆発！アイドルの特技がぶっ飛びすぎてやばかったww #2',
    viewCount: 1569,
    memberNames: ['美和花樺', '双葉みきな', '大嶋ひかり', '南ララ', '雪咲みうな'],
  },
  {
    id: 'E2-EtIbA7No',
    title: '謎すぎる特技を披露するメンバーにスタジオ大爆笑www #1',
    viewCount: 2260,
    memberNames: ['桜瀬もえ', '夏生のん', '渡辺栞', '藤咲はな', '水越菜波'],
  },
];
